name: Run Acceptance Tests

on:
  push:
    branches: [ "feature/GHA_for_acceptance_test" ]
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Install Dependencies
      run: |
        go get -u github.com/onsi/ginkgo/v2/ginkgo
        go get -u github.com/onsi/gomega/...

    - name: Run Tests
      run: |
        make test
